name: skript-fishing
main: io.github.fusezion.skriptfishing.SkriptFishing
version: @version@
api-version: 1.13
authors: [Fusezion, SkAlternative]
description: Enables the easy modification of fishing within Skript.
website: https://github.com/Fusezion/skript-fishing
softdepend: [Skript]
